services:
    db:
        image: mongo
        restart: on-failure
        ports:
            - 27017:27017

    app:
        build: ./backend
        restart: on-failure
        volumes:
        - myimage:/app/static/images
        ports:
            - 8000:8000
        develop:
            watch:
                - action: sync
                  path: ./app.py
                  target: /app/app.py
volumes:
  myimage:
